# -*- coding: utf-8 -*-
"""NewsCategorizationML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eqdOAjHqpI8f9rb2S_XaeZW26Dwd3UJN
"""

import pandas as pd
import re
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

data=pd.read_csv('/content/drive/MyDrive/bilstm_news.csv')

data.columns

data.drop('Unnamed: 0',axis=1,inplace=True)

data.shape

data['Category'].value_counts()

train_data=data

train_data.columns

train_data['Category'].value_counts()

##Data Preprocessing ###

names=['Politics','Business','Sport','Science','Health','Entertainment','Tech']

Xtrain,Xtest,ytrain,ytest=train_test_split(train_data['Text'],train_data['Category'],test_size=0.2,random_state=43)

ytest.value_counts()

from sklearn.pipeline import Pipeline 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
model_lr = Pipeline([('tfidf', TfidfVectorizer()),
                         ('clf2', LogisticRegression(solver='newton-cg', multi_class='multinomial')),
                         ])

model_lr = model_lr.fit(Xtrain, ytrain)
predicted = model_lr.predict(Xtest)

from sklearn import metrics
metrics.accuracy_score(ytest, predicted)

print(metrics.classification_report(ytest, predicted, target_names=sorted(names)))

document_health=["In today's segment of Boost Your Immunity, we bring to you a tasty and healthy recipe of Black-eyed bean salad. It is easy to make and has high nutritional value." ]
document_sport=["The International Cricket Council (ICC) said that Sourav Ganguly has replaced Anil Kumble as chairman of the ICC Cricket Committee after the latter stepped down having served a maximum of three, three-year terms."]
document_business=['Cryptocurrency prices reduced further on Tuesday as investors continued to book profits to make the most of the recent rally. Check the latest cryptocurrency prices and trends.']
document_tech=['Motorola ventured into the tablet market recency with the Moto Tab G20. The tablet was launched in the budget category, but now Motorola is planning to unveil a slightly more premium tablet.']
document_ent=['Akshay Kumar and Katrina Kaif-starrer Sooryavanshi is going strong at the box office. The film earned Rs 242.08 crore worldwide on Day 12 of its release.']
document_politics=['Court asks MP Police to register case against BJP leader for posting defamatory content against Cong MLA']
tfidf=TfidfVectorizer()
tfidf=tfidf.fit_transform(document_ent)
model_lr.predict(document_ent)[0]

import pickle

pickle.dump(model_lr, open("model_lr.pkl", "wb"))